### ISSUE TITLE
Remove a column or a row from a table.

### ISSUE THREAD

**Issue by ooredroxoo** [CSS-Tricks/The-Printliminator#1]
Hi, 
Would be nice to have a way to remove an whole column or a row from a table.

Thinking now would be two more buttons that would have this functions, so when clicking over a cell they would loockup for the parent row in the rows case and hide it, or all the way up getting a reference of all rows to loop in each removing the cell at the index of the column that should be removed.

Would be a awesome addition.

**Comment by Mottie** [comment]
@ooredroxoo The latest version (v3.1.0) includes keyboard keys that allow you to traverse the elements (parent, first child & next/prev sibling). See the screenshot in the readme for a better description.
