### ISSUE TITLE
2014 update for https, jquery, etc

### ISSUE THREAD

**Issue by focusaurus** [CSS-Tricks/The-Printliminator#2]
I found the google code repo for this before finding the github one, so I just posted the issue over there first:

https://code.google.com/p/printliminator/issues/detail?id=1

>It seems maybe this project hasn't been updated since 2010 (?). However, I absolutely love this bookmarklet, but it is working on fewer and fewer sites as time goes by. I suspect either moving away from jQuery or properly loading a non-conflicting modern version may help. I'd also like to see protocol relative urls to load the resources so http and https sites work.

**Comment by Mottie** [comment]
I just updated Printliminator! I removed the protocols from the links, but because jQuery is loaded from Google, it still won't work on GitHub. 

I do have plans to remove the jQuery dependency when I get more free time, so that should make it even better :grin:

**Comment by focusaurus** [comment]
Awesome. Thanks, @Mottie !

**Comment by Mottie** [comment]
I'm still working on the extension... but in the mean time, v3.1.0 is available:

* New design by Chris!
* No more jQuery dependency
* Draggable
* Keyboard commands included.
