### ISSUE TITLE
Closes Opera Browser instead of printing

### ISSUE THREAD

**Issue by Texas-Rose** [CSS-Tricks/The-Printliminator#21]
I use Opera Browser on Windows 10 PC. Until the past couple of days, PrintEliminator worked great. Now, when I try to open it to print, it starts but then quickly closes the browser. Can't set options such as print, save as PDF, etc. like before.

**Comment by Mottie** [comment]
Hi @Texas-Rose!

I just tested the extension in Opera v55.0.2994.37 and did not see this issue. Try disabling all the other extensions and re-enabling them one-by-one to see which one is causing the issue.

**Comment by Texas-Rose** [comment]
Works now. Tks Mottie.
